services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports: 
      - "3333:3333"
    depends_on:
      - bd
    environment:
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://decideai:decideai123@bd:5432/decideai}
  bd:
    build:
      context: ./bd
    ports:
      - "5432:5432"
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
