services:
  backend:
    build:
      context: ./backend
    ports: 
      - "3333:3333"
    depends_on:
      - bd
    environment:
      - POSTGRES_URL=${POSTGRES_URL:-postgresql://decideai:decideai123@bd:5432/decideai}
    networks:
      - internal_network

  bd:
    build:
      context: ./bd
    networks:
      - internal_network
  
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge