apiVersion: v1
kind: PersistentVolume
metadata:
  name: decideai-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/decideai"
    type: DirectoryOrCreate